package de.postkisten.keygenerator

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter

private val DhlRed = Color(0xFFD40511)
private val DhlYellow = Color(0xFFFFCC00)
private val DhlDarkRed = Color(0xFF9B0008)

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent { KeyGeneratorTheme { KeyGeneratorScreen() } }
    }
}

@Composable
private fun KeyGeneratorTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = androidx.compose.material3.lightColorScheme(
            primary = DhlRed,
            secondary = DhlDarkRed,
            background = DhlYellow,
            surface = Color.White,
            onPrimary = Color.White,
            onBackground = Color.Black,
        ),
        content = content,
    )
}

@Composable
private fun KeyGeneratorScreen() {
    var generated by remember { mutableStateOf(TeamLeaderKeyGenerator.generate()) }
    var copied by remember { mutableStateOf(false) }
    val clipboard = LocalClipboardManager.current

    Column(
        Modifier.fillMaxSize().background(DhlYellow).padding(18.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(18.dp),
    ) {
        Spacer(Modifier.height(12.dp))
        Text(
            "TEAMLEITER-KEYGENERATOR",
            color = DhlRed,
            fontWeight = FontWeight.Black,
            fontSize = 25.sp,
            textAlign = TextAlign.Center,
        )
        Text("AV-Erfassung", fontSize = 19.sp, fontWeight = FontWeight.Bold)
        Card(
            Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(14.dp),
            colors = CardDefaults.cardColors(containerColor = Color.White),
        ) {
            Column(
                Modifier.fillMaxWidth().padding(18.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(13.dp),
            ) {
                Text("AKTUELLER SCHLÜSSEL", fontWeight = FontWeight.Bold, color = DhlDarkRed)
                SelectionContainer {
                    Text(
                        generated.key,
                        fontFamily = FontFamily.Monospace,
                        fontWeight = FontWeight.Black,
                        fontSize = 21.sp,
                        textAlign = TextAlign.Center,
                    )
                }
                Text("Erstellt: ${format(generated.createdAtUtc)} Uhr", textAlign = TextAlign.Center)
                Text(
                    "Gültig bis: ${format(generated.expiresAtUtc)} Uhr",
                    color = DhlRed,
                    fontWeight = FontWeight.Bold,
                    textAlign = TextAlign.Center,
                )
                Text("Gültigkeitsdauer: 9 Stunden", fontSize = 14.sp)
            }
        }
        ActionButton("NEUEN KEY ERSTELLEN", {
            generated = TeamLeaderKeyGenerator.generate()
            copied = false
        }, filled = true)
        ActionButton(if (copied) "KEY KOPIERT" else "KEY KOPIEREN", {
            clipboard.setText(AnnotatedString(generated.key))
            copied = true
        }, filled = false)
        Spacer(Modifier.weight(1f))
        Text(
            "Nur für berechtigte Teamleiter. Diese App darf nicht auf Mitarbeitergeräten installiert werden.",
            color = DhlDarkRed,
            fontWeight = FontWeight.Bold,
            textAlign = TextAlign.Center,
            fontSize = 14.sp,
        )
        Text("Version 1.0.0", fontSize = 12.sp)
    }
}

@Composable
private fun ActionButton(label: String, onClick: () -> Unit, filled: Boolean) {
    Button(
        onClick = onClick,
        modifier = Modifier.fillMaxWidth().height(66.dp),
        shape = RoundedCornerShape(10.dp),
        colors = ButtonDefaults.buttonColors(
            containerColor = if (filled) DhlRed else Color.White,
            contentColor = if (filled) Color.White else DhlRed,
        ),
    ) { Text(label, fontWeight = FontWeight.Black, fontSize = 17.sp) }
}

private val formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm:ss")
    .withZone(ZoneId.systemDefault())
private fun format(millis: Long) = formatter.format(Instant.ofEpochMilli(millis))
