package de.avm.errors

enum class AvmError(val code: String) {
    PACKAGE_SIGNATURE_INVALID("AVM-PKG-1001"),
    PACKAGE_KEY_REVOKED("AVM-PKG-1002"),
    PACKAGE_PATH_UNSAFE("AVM-PKG-1003"),
    PACKAGE_SCHEMA_INVALID("AVM-PKG-1004"),
    CONTRACT_VERSION_UNSUPPORTED("AVM-CSV-2001"),
    REQUIRED_FIELD_MISSING("AVM-CSV-2002"),
    SAME_REVISION_DIGEST_CONFLICT("AVM-CSV-2003"),
    REVISION_CHAIN_BROKEN("AVM-CSV-2004"),
    PAYLOAD_DIGEST_INVALID("AVM-CSV-2005"),
    CSV_DIGEST_MISMATCH("AVM-CSV-2006"),
    BACKUP_SIGNATURE_INVALID("AVM-BKP-3001"),
    BACKUP_TENANT_MISMATCH("AVM-BKP-3002"),
    DATABASE_SCHEMA_INCOMPATIBLE("AVM-BKP-3003"),
    BACKUP_INCOMPLETE("AVM-BKP-3004"),
    BACKUP_MANIFEST_INVALID("AVM-BKP-3005"),
    BACKUP_KEY_REVOKED("AVM-BKP-3006"),
    ABI_VERSION_UNSUPPORTED("AVM-ABI-4001"),
    FUNCTION_TABLE_INCOMPLETE("AVM-ABI-4002"),
    MODULE_ID_MISMATCH("AVM-ABI-4003"),
    DIAGNOSTIC_FIELD_FORBIDDEN("AVM-DIA-5001"),
    COMPATIBILITY_UNSATISFIED("AVM-COMP-6001"),
}

data class AvmFailure(
    val error: AvmError,
    val message: String,
    val location: String? = null,
)
